# base_cnn.yaml

# Network configuration for CNN
network:
  type: CNN
  input_dim: 300  # Image size (300x300)
  
conv_layers:
  - type: Conv2D
    in_channels: 3
    out_channels: 32
    kernel_size: 5
    padding: 2
    batch_norm: true
    activation: ReLU
    pool_kernel_size: 5
    pool_stride: 5
  - type: Conv2D
    in_channels: 32
    out_channels: 64
    kernel_size: 5
    padding: 2
    batch_norm: true
    activation: ReLU
    pool_kernel_size: 5
    pool_stride: 5
  - type: Conv2D
    in_channels: 64
    out_channels: 128
    kernel_size: 3
    padding: 1
    batch_norm: true
    activation: ReLU
    pool_kernel_size: 2
    pool_stride: 2

# Fully connected layers
fc_layers:
  - units: 576
    activation: ReLU
    dropout: 0.1
  - units: 144
    activation: ReLU
    droupout: 0.1
  - units: 64
    activation: ReLU


# Optimizer settings
optimizer:
  type: Adam
  learning_rate: 0.001
  decay: 0.0001

# Loss function
loss_function: CrossEntropyLoss

# Training settings
training:
  batch_size: 32
  epochs: 10

# Data paths
data:
  train_data: path/to/train_data
  test_data: path/to/test_data
  validation_data: path/to/validation_data

# General settings
seed: 42
gpu: true
